config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "lists#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
    has_many :bookmarks
    has_many :movies, through: :bookmarks, dependent: :destroy

    validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :bookmarks

    validates :title, presence: true, uniqueness: true
    validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    
    def index
        @lists = List.all
    end

    def new
        @list = List.new
    end

    def show
        @list = List.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-3">
      <a href="/">
        <img alt="logo" class="logo" src="/assets/">
      </a>  
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to 'My Lists', lists_path %>
          </li>
          <li class="nav-item active">
            <%= link_to 'New List', new_list_path %>
          </li>
        </ul>
      </div>
    </div>

  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
    <div class="container">
      <h1>Create your own movie-lists <strong>fast</strong> and <strong>easy</strong>!</h1>
      <p>Start now creating your own!</p>
        <%= link_to "Create new list", new_list_path, class: 'btn btn-flat'%>

    </div>
  </div>
    
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h3>My lists</h3>

<ul>
    <% for list in @lists %>
        <li><%= link_to @lists.name, list_path(list) %></li>
    <% end %>
</ul>

app/views/lists/new.html.erb
<div class='container py-5'>
    <div class="row">
        <div class="col-12 col-md-6 offset-lg-3">
            <div class="bg-white rounded p-3 shadow">
                <h3>CREATE NEW LISTS</h3>
                <%= simple_form_for @list do |f| %>
                    <%= f.input :name %>
                    <%= f.submit class: 'btn btn-primary' %>
                <% end %>
            </div>
        </div>
    </div>
</div>